# Generated by Django 2.2.13 on 2020-06-27 22:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoriUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('equip', models.TextField()),
                ('want', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('fixed_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
